---

- name: "add additional apt keys"
  apt_key:
    id: "{{ item.key.id | default(omit) }}"
    url: "{{ item.key.url | default(omit) }}"
    keyserver: "{{ item.key.keyserver | default(omit) }}"
    validate_certs: "{{ item.key.validate_certs | default(omit) }}"
    state: "present"
  when:
    - "item.key is defined"
    - "item.key"
    - "item.key.id is defined and item.key.id or item.key.url is defined and item.key.url"
  with_items:
    - "{{ oracle_java_repo_list }}"

- name: "add additional apt repositories"
  apt_repository:
    repo: "{{ item.repo }}"
    state: "present"
  when:
    - "item.repo is defined"
    - "item.repo"
  with_items:
    - "{{ oracle_java_repo_list }}"

- name: "accept Oracle's Java License"
  debconf:
    name: "oracle-java{{ oracle_java_major_version }}-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"

- name: "install packages"
  apt:
    name: "{{ item }}"
    update_cache: "{{ oracle_java_update_cache|default(omit) }}"
    cache_valid_time: "{{ oracle_java_cache_valid_time|default(omit) }}"
    state: "present"
    default_release: "{{ oracle_java_default_release|default(omit) }}"
  with_items:
    - "{{ oracle_java_package_list }}"
